// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpVkfB61HPy_3PNNWV-ufl2tKDAJ9uPk4',
    appId: '1:403022773309:web:76efa43a6f1cc498653e54',
    messagingSenderId: '403022773309',
    projectId: 'prakflutterfirebase-381e5',
    authDomain: 'prakflutterfirebase-381e5.firebaseapp.com',
    storageBucket: 'prakflutterfirebase-381e5.appspot.com',
    measurementId: 'G-XJT2NKJ9HC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBirm1gPaR8Gezdc3AyQCctvm8X_r5Y-Qw',
    appId: '1:403022773309:android:19b89b889f62c1cf653e54',
    messagingSenderId: '403022773309',
    projectId: 'prakflutterfirebase-381e5',
    storageBucket: 'prakflutterfirebase-381e5.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpVkfB61HPy_3PNNWV-ufl2tKDAJ9uPk4',
    appId: '1:403022773309:web:f59f5c13147084b7653e54',
    messagingSenderId: '403022773309',
    projectId: 'prakflutterfirebase-381e5',
    authDomain: 'prakflutterfirebase-381e5.firebaseapp.com',
    storageBucket: 'prakflutterfirebase-381e5.appspot.com',
    measurementId: 'G-78K5LNP9M0',
  );
}
